server:
  port: 8888

spring:
  profiles:
    active: native, git, vault
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        native:
          searchLocations: file://${user.home}/config-repo
        git:
          uri: https://github.com/waynefoundation/spring-cloud-config-repo
        vault:
          host: vault-service
          port: 8080
          scheme: http
          backend: secret
          defaultKey: application
          profileSeparator: ','
          kvVersion: 2
          skipSslValidation: true
          timeout: 5

management:
  endpoints:
    web:
      exposure:
        include: info, health, env