server:
  port: 8888

spring:
  profiles:
    active: native, git, vault
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        native:
          searchLocations: file://${user.home}/config-repo
        git:
          uri: https://github.com/waynefoundation/spring-cloud-config-repo
        vault:
          port: 8200
          host: vault-service

management:
  endpoints:
    web:
      exposure:
        include: info, health, env